"""first migration

Revision ID: 8031cae8e9c2
Revises: 
Create Date: 2024-01-04 17:19:55.338510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8031cae8e9c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('music_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_artist'), 'posts', ['artist'], unique=False)
    op.create_index(op.f('ix_posts_comment'), 'posts', ['comment'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_image'), 'posts', ['image'], unique=False)
    op.create_index(op.f('ix_posts_music'), 'posts', ['music'], unique=False)
    op.create_index(op.f('ix_posts_music_id'), 'posts', ['music_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_music_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_music'), table_name='posts')
    op.drop_index(op.f('ix_posts_image'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_comment'), table_name='posts')
    op.drop_index(op.f('ix_posts_artist'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
